### ISSUE TITLE
allow to pass options directly from `validates`

### ISSUE THREAD

**Issue by vendethiel** [amatsuda/kawaii_validation#1]
Hi! nice gem, cleans up a bit.
I'd love to be able to do this : 

``` ruby
validates :password, if: :update_password? do
  confirmation
end
```

**Comment by vendethiel** [comment]
hi @amatsuda , are you interested in this? I can maybe try a PR if that sounds reasonable to you

**Comment by amatsuda** [comment]
Yep, seems not bad :smile_cat:
